export enum ScreenName {
  HomeFeed = 'Homefeed',
  NetworkChatScreen = "Homefeed",
  CommunityChatScreen = "Homefeed",
  CommunityHybridChatScreen = "Homefeed",
  ExploreFeed = 'ExploreFeed',
  Chatroom = 'Chatroom',
  FileUpload = 'FileUpload',
  CarouselScreen = 'CarouselScreen',
  PollResult = 'PollResult',
  CreatePollScreen = 'CreatePollScreen',
  ImageCropScreen = 'ImageCropScreen',
  VideoPlayer = 'VideoPlayer',
  SearchInChatroom = 'SearchInChatroom',
  ChatBotInitiateScreen = 'ChatBotInitiateScreen',
  Report = 'Report',
  ImageScreen = 'ImageScreen',
  ViewParticipants = 'ViewParticipants',
  AddParticipants = 'AddParticipants',
  DmAllMembers = 'DMAllMembers',
  GroupFeed = 'GroupFeed',
  DmFeed = 'DMFeed',
}
